services:
  # May require you to login to ghcr.io first:
  # $ docker login ghcr.io --username=<username>
  # If you need a token, a short-lived classic token with read:packages is enough.
  zizmor:
    image: ghcr.io/zizmorcore/zizmor:1.25.2
    command: --quiet --quiet --min-severity=low .github
    working_dir: /opt/infection
    volumes:
      - .:/opt/infection

  php83:
    build:
      context: devTools
      args:
        PHP_VERSION: '8.3'
        XDEBUG_VERSION: '3.4.1'
    volumes:
      - .:/opt/infection
