#!/usr/bin/env bash

cd tests/e2e

failure="false"

if [ -f error.log ]
then
    :> error.log
fi

touch error.log

for dir in  */
do
    cd "$dir"
    echo -e "\n$dir\n";

    if [ -f composer.json ] || [ -f composer.lock ]
    then
        composer install > /dev/null 2>&1
    fi

    if [ -f "run_tests.bash" ]
    then
        output="$(bash run_tests.bash)"
    else
        output="$(bash ../standard_script.bash ${1:-build/bin/infection.phar})"
    fi

    if [ $? != 0 ]
    then
        failure="true"
        echo "$dir" >> ../error.log
        echo "$output" >> ../error.log
        echo "" >> ../error.log
    fi
    cd ..
done

if [ $failure = "true" ]
then
    echo "One of the e2e tests failed, check the logs";
    cat error.log
    exit 1
fi

echo -e "\nSuccess"
exit 0
