FROM php:7.4-cli

RUN pecl install xdebug-beta && docker-php-ext-enable xdebug
RUN apt-get update && apt-get install -y --no-install-recommends \
    expect git zip \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN useradd --home-dir /opt/infection --shell /bin/bash infection

COPY devTools/memory-limit.ini /usr/local/etc/php/conf.d/memory-limit.ini

USER infection
