FROM php:7.0-cli

RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN apt-get -y update && apt-get install -y expect git zip
RUN curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN useradd --home-dir /opt/infection --shell /bin/bash infection

USER infection
