FROM php:7.4-cli-alpine

RUN set -eux; \
    apk add --no-cache --virtual .build-deps \
        ${PHPIZE_DEPS} \
        build-base \
    ; \
    pecl install xdebug; \
    pecl clear-cache; \
    docker-php-ext-enable xdebug ;\
    runDeps="$( \
        scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
            | tr ',' '\n' \
            | sort -u \
            | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
    )"; \
    apk add --no-cache --virtual .phpexts-rundeps ${runDeps}; \
    apk del .build-deps

RUN apk add --no-cache \
        ncurses \
        make \
        bash \
        expect \
        zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY devTools/memory-limit.ini ${PHP_INI_DIR}/conf.d/memory-limit.ini

RUN adduser -h /opt/infection -s /bin/bash -D infection

USER infection
