---
config:
    layout: elk
---
flowchart TB
    %% Blocks
    SourceCollection["Source Collection"]
    ArtefactCollection["Artefact Collection"]

    AstParsing["AST Parsing"]
    AstEnrichment["AST Enrichment"]

    MutationGeneration["Mutation Generation"]
    HeuristicSuppression["Heuristic Suppression"]
    MutantMaterialisation["Mutant Materialisation"]
    MutantEvaluation["Mutant Evaluation"]

    Reporting["Reporting"]

    %% Flow
    SourceCollection --> ArtefactCollection
    ArtefactCollection --> AstParsing
    AstParsing --> AstEnrichment
    AstEnrichment --> MutationGeneration
    MutationGeneration --> HeuristicSuppression
    HeuristicSuppression --> MutantMaterialisation
    MutantMaterialisation --> MutantEvaluation
    MutantEvaluation --> Reporting

    %% Groups
    subgraph MutationAnalysis["Mutation Analysis"]
        AstProcessing
        MutationGeneration
        MutationEvaluation
    end

    subgraph AstProcessing["AST Processing"]
        AstParsing
        AstEnrichment
    end

    subgraph MutationEvaluation["Mutation Evaluation"]
        HeuristicSuppression
        MutantAnalysis
    end

    subgraph MutantAnalysis["Mutant Analysis"]
        MutantMaterialisation
        MutantEvaluation
    end

%% Styling
    style SourceCollection fill:#f1f5f9,stroke:#64748b
    style ArtefactCollection fill:#f1f5f9,stroke:#64748b
    style Reporting fill:#f1f5f9,stroke:#64748b

    style MutationAnalysis fill:#f8fafc,stroke:#cbd5e1

    style AstProcessing fill:#eef2ff,stroke:#6366f1
    style AstParsing fill:#c7d2fe,stroke:#4f46e5
    style AstEnrichment fill:#c7d2fe,stroke:#4f46e5

    style MutationGeneration fill:#99f6e4,stroke:#0d9488

    style MutationEvaluation fill:#fff7ed,stroke:#ea580c
    style HeuristicSuppression fill:#fed7aa,stroke:#c2410c

    style MutantAnalysis fill:#fff1f2,stroke:#e11d48
    style MutantMaterialisation fill:#fecdd3,stroke:#be123c
    style MutantEvaluation fill:#fecdd3,stroke:#be123c
