name: Coding Standards

on:
  pull_request:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          # Should use the lowest supported version to ensure the CS-Fixer does
          # not get confused and apply a rule that would break on lower supported
          # versions.
          php-version: 8.2

      - name: Configure PHP-CS-Fixer GitHub Actions cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ./var/cache/php-cs-fixer
          key: "8.2-php-cs-fixer-${{ github.run_id }}"
          restore-keys: "php-cs-fixer"

      - name: Run PHP-CS-Fixer
        run: make cs-check
